### ISSUE TITLE
I would like to modify your code.

### ISSUE THREAD

**Issue by Artem-Schander** [wrzlbrmft/imapcopy#4]
Hi Matthias,

the GNU GPL v3 license says clearly that changing the source is not allowed. Is there any possibility to change that?
I would like to develop an (possibly open source) GUI on top of your script. For that purpose it would be nice, if i could change the structure (psr 4 autoload).

Please let me know if it is possible.

**Comment by wrzlbrmft** [comment]
Hi Artem, under GPL v3 you are free to copy, change and modify the code as long as all changes remain under the GPL v3, see: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)
Just fork and modify the code and file a pull request in the end.

**Comment by Artem-Schander** [comment]
I see. Thanks for the Info.
In the meantime i have my own implementation at 70%, but thanks anyways.
However, cool script. Keep up the work.
